meta_product_name: "CareOn"
meta_title: "CareOn Life | Dashboard"
meta_description: "Relevant description"
meta_image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?ixlib=rb-0.3.5&s=ec623087db695bb95cb4da16c3470aeb&auto=format&fit=crop&w=1050&q=80"
twitter_account: "@product_twitter_account"
