meta_product_name: "CareOn"
meta_title: "CareOn Life | Dashboard"
meta_description: "Relevant description"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
