meta_product_name: "CareOn"
meta_title: "CareOn | Gardez le lien avec vos patients"
meta_description: "CareOn est une solution de suivi patient, au service des unités de chirurgie ambulatoire"
meta_image: "cover-meta.jpg"
twitter_account: "@product_twitter_account"
