meta_product_name: "CareOn"
meta_title: "CareOn Life | Dashboard"
meta_description: "Relevant description"
meta_image: "https://www.careon.life/assets/cover-meta.jpg"
twitter_account: "@product_twitter_account"
